SETTINGS = {
    'analise-base-xlsx':'C:/Users/unig.ead/Documents/analysis/data/analise-base-xlsx.xlsx',
    'filtros':{
        'POLO': 'Nova Iguaçu',
        'MODALIDADE': 'G'
    },
    'entrada':"2"
}

COURSE_MAPPER = {
    "Serviço Social": "SERV.SOC.",
    "Gestão da Tec. da Informação": "GEST. TI",
    "Educação Física Bacharelado": "ED.FI.BACH",
    "Segurança Pública": "SEG. PUBL.",
    "Farmácia": "FARMAC.",
    "Fisioterapia": "FISOTERAP.",
    "Logística": "LOGIST.",
    "Engenharia Elétrica": "ENG. ELET.",
    "Administração": "ADM",
    "Gestão Financeira": "GEST. FINAN",
    "Biomedicina": "BIOM",
    "Pedagogia": "PEDAG.",
    "Marketing": "MARKET.",
    "Engenharia Mecânica": "ENG. MEC.",
    "Engenharia Mêcanica": "ENG. MEC.",  # correção de acento
    "Letras": "LETRAS",
    "Gestão de Recursos Humanos": "REC. HUM.",
    "Ciência da Computação": "CIE. COMP.",
    "Gestão Ambiental": "GEST. AMB.",
    "Análise e Des. de Sistemas": "ADS",
    "Ciências Contábeis": "C.CONTAB.",
    "Educação Física - Bacharelado": "ED.FI.BACH",
    "Educação Fisíca Lic": "ED.FI.LIC",
    "Redes de Computadores": "REDES.COM.",
    "Processos Gerenciais": "PROC. GER.",
    "Comércio Exterior": "COMEX",
    "Gestão Pública": "GEST. PUBL.",
    "Engenharia de Produção": "ENG.PROD",
    "Educação Física Licenciatura": "ED.FI.LIC",
    "Educação Fisíca - Lic": "ED.FI.LIC",
    "História": "HISTORIA",
    "Matemática": "MATEM.",
    "Gestão Comercial": "GEST. COM.",
    "Análise E Des. De Sistemas":'Ads',
    "Ciência Da Computação":"Cie. Comp.",
    "Engenharia De Produção": "Eng.Prod",
    "Gestão Da Tec. Da Informação": "Gest. Ti",
    "Redes De Computadores": "Redes.Com.",
    "Gestão De Recursos Humanos":"Rec. Hum."
}

# mapper_professores.py

PROFESSOR_MAPPER = {
    "Rodrigo Bandeira Marra": "Rodrigo Bandeira Marra",
    "Carolina Nunes Santos": "Carolina Nunes Santos",
    "Marcia Cristina Roma de Vasconcellos": "Marcia Cristina Roma de Vasconcellos",
    "Suziane Hermes de Mendonça Soares": "Suziane Hermes de Mendonça Soares",
    "Denise Moraes do Nascimento Vieira": "Denise Moraes do Nascimento Vieira",
    "Laércio dos Santos Martins": "Laércio dos Santos Martins",
    "Marcos Cruz de Azevedo": "Marcos Cruz de Azevedo",
    "Ronaldo Paulucci de Assis": "Ronaldo Paulucci de Assis",
    "Hamilcar Pereira da Silva": "Hamilcar Pereira da Silva",
    "Jorge Antônio Filho": "Jorge Antônio Filho",
    "Aline Figueira Lira": "Aline Lira",
    "Jailton Luiz Vieira": "Jailton Luiz Veira",
    "Eliane Ferreira de Souza Ribeiro": "Eliane Ferreira de Souza Ribeiro",
    "Eliel Bezerra de Lima Junior": "Eliel Bezerra de Lima Junior",
    "Roberta Rodrigues Teixeira de Castro": "Roberta Rodrigues Teixeira de Castro",
    "Denilson Costa Soares": "Denilson Costa Soares",
    "Sidnei Castilhos Rodrigues": "Sidnei Castilhos Rodrigues",
    "Rogério da Silva Guimarães": "Rogério da Silva Guimarães",
    "Tatiana Frazão Silva": "Tatiana Frazão Silva",
    "Rosalva Maria Gomes de Araújo Oliveira": "Rosalva Maria Gomes de Araújo Oliveira",
    "Alex Sandro Rodrigues Baiense": "Alex Sandro Rofrigues Baiense",
    "Fabiana Sousa Pugliese": "Fabiana Puglise",
    "Fabiano Lacerda Carvalho": "Fabiano Lacerda Carvalho",
    "Nylza Maria Tavares Gonçalves": "Nylza Maria Tavares Gonçalves",
    "Alcione Silva de Carvalho": "Alcione da Silva Carvalho",
    "Madson da Silva Matos": "Madson da Silva Matos",
    "Washington da Silva Matos": "Washington da Silva Matos",
    "Alan Jeferson De Oliveira Da Silva": "Alan Jefferson De Oliveira Da Silva",
    "Carlos Rogério Domingos Araújo Silveira": "Carlos Rogério Domingos Araújo Silveira",
    "Luiz Eduardo Santos Nunes": "Luiz Eduardo Santos Nunes",
    "Telmo Viana Rodrigues": "Telmo Viana Rodrigues",
    "Paulo Alex Nacif Lube": "Paulo Alex Nacif Lube",
    "Vazio": "Vazio",
    "Marco Aurélio Gaspar Lessa": "Marco Aurélio Gaspar Lessa",
    "Andréa Matias Evangelho": "Andrea Mattias Evangelho",
    "Lucas Alves Pereira": "Lucas Alves Pereira",
    "João Manoel Lopes de Lima": "João Manuel Lopes de Lima",
    "Selma Sant'Anna Da Fonseca": "Selma Sant Anna Da Fonseca Sardinha",
    "Giana Laport Alves de Souza": "Giana Laport Alves de Souza",
    "Isis Regina Dos Santos Mendes": "Isis Regina Mendes",
    "Simone Christina Rebello Barros": "Simone Christina Rebello Barros",
    "Kátia Lúcia Fentanez Rodrigues Mattos": "Kátia Lúcia Fentanez Rodrigues Mattos",
    "Rejane de Oliveira Freitas Silveira": "Rejane de Oliveira Freitas Silveira",
    "Deivid Costa Soares": "Deivid Costa Soares",
    "Filomena Maria Rates Soares": "Filomena Maria Rates Soares",
    "Fernanda Barbosa Salgueiro": "Fernanda Barbosa Salgueiro",
    "Telma Ardoim": "Telma Ardoim",
    "Erick de Sousa Marouço": "Érick Marrouco",
    "Wallace da Silva Carvalho": "Wallace da Silva Carvalho",
    "Ary Sergio Coutinho Barbosa Junior": "Ary Sergio Coutinho Barbosa Junior",
    "Camila Ferreira de Souza Costa": "Camila Ferreira de Souza Costa",
    "André Lourenço da Silveira": "André Lourenço da Silva",
    "Douglas Batista da Silva": "Douglas Batista da Silva",
    "Cristiane Pires Motta": "Cristiane Pires Motta",
    "Raphael Pacheco da Rocha": "Raphael Pacheco da Rocha",
    "Athus Martins Salgado do Amaral": "Athus Martins Salgado do Amaral",
    "Carlos Figueiredo Veiga": "Carlos Figueiredo Veiga",
    "Lucas Antunes Faria Vieira": "Lucas Antunes Faria Vieira",
    "Joel Teixeira Dutra": "Joel Teixeira Dutra",
    "Letícia Ecard Rocha": "Letícia Ecard",
    "João Jorge Sarto Neto": "João Jorge Sarto Neto",
    "Wellington Marinho Pereira": "Wellington Marinho Pereira",
    "Mônica Saad Madeira": "Mônica Saad Madeira",
    "Rodolfo Gomes de Araujo Oliveira": "Rodolfo Gomes de Araujo Oliveira",
    "Rafael da Silva Moreira": "Rafael da Silva Moreira",
    "Luciano Roberto Padilha de Andrade": "Luciano Roberto Padilha de Andrade",
    "Jaime Luciano de Souza": "Jaime Luciano de Souza",
    "Vânia das Graças de Vasconcellos": "Vânia das Graças de Vasconcellos",
    "Luciana Santos de Oliveira": "Luciana Santos de Oliveira",
    "Fernando Salgado Amaral": "Fernando Salgado do Amaral",
    "Thiago Pereira de Abreu": "Tiago Pereira de Abreu",
    "Rafaela de Oliveira Ferreira": "Rafaela de Oliveira Ferreira",
    "Arith Ramos dos Santos": "Arith Ramos dos Santos"
}


DICIPLINA_MAPPER = {
    'Marketing Digital E Mídias Sociais - Optativa':"Marketing Digital- Optativa",
    'Gestão De Ti':"Gestão De Tecnologia Da Informação",
    "Raciocínio Lógico":"Raciocínio Lógico (Tec´S)",
}