TEACHER_MAPPING = {
    'rodrigo bandeira marra': 'Rodrigo Bandeira Marra',
    'carolina nunes santos': 'Carolina Nunes Santos',
    'marcia cristina roma de vasconcellos': 'Marcia Cristina Roma de Vasconcellos',
    'suziane hermes de mendonça soares': 'Suziane Hermes de Mendonça Soares',
    'denise moraes do nascimento vieira': 'Denise Moraes do Nascimento Vieira',
    'laércio dos santos martins': 'Laércio Dos Santos Martins',
    'marcos cruz de azevedo': 'Marcos Cruz de Azevedo',
    'ronaldo paulucci de assis': 'Ronaldo Paulucci de Assis',
    'hamilcar pereira da silva': 'Hamilcar Pereira da Silva',
    'jorge antônio filho': 'Jorge Antônio Filho',
    'aline figueira lira': 'Aline Lira',
    'jailton luiz vieira': 'Jailton Luiz Veira',
    'eliane ferreira de souza ribeiro': 'Eliane Ferreira de Souza Ribeiro',
    'eliel bezerra de lima junior': 'Eliel Bezerra de Lima Junior',
    'roberta rodrigues teixeira de castro': 'Roberta Rodrigues Teixeira de Castro',
    'denilson costa soares': 'Denilson Costa Soares',
    'sidnei castilhos rodrigues': 'Sidnei Castilhos Rodrigues',
    'rogério da silva guimarães': 'Rogério da Silva Guimarães',
    'tatiana frazão silva': 'Tatiana Frazão Silva',
    'rosalva maria gomes de araújo oliveira': 'Rosalva Maria Gomes de Araújo Oliveira',
    'alex sandro rodrigues baiense': 'Alex Sandro Rofrigues Baiense',
    'fabiana sousa pugliese': 'Fabiana Puglise',
    'fabiano lacerda carvalho': 'Fabiano Lacerda Carvalho',
    'nylza maria tavares gonçalves': 'Nylza Maria Tavares Gonçalves',
    'alcione silva de carvalho': 'Alcione da Silva Carvalho',
    'madson da silva matos': 'Madson da Silva Matos',
    'washington da silva matos': 'Washington da Silva Matos',
    'alan jeferson de oliveira da silva': 'ALan Jefferson De Oliveira Da Silva',
    'carlos rogério domingos araújo silveira': 'Carlos Rogério Domingos Araújo Silveira',
    'luiz eduardo santos nunes': 'Luiz Eduardo Santos Nunes',
    'telmo viana rodrigues': 'Telmo Viana Rodrigues',
    'paulo alex nacif lube': 'Paulo Alex Nacif Lube',
    'marco aurélio gaspar lessa': 'Marco Aurélio Gaspar Lessa',
    'andréa matias evangelho': 'Andrea Mattias Evangelho',
    'lucas alves pereira': 'Lucas Alves Pereira',
    'joão manoel lopes de lima': 'João Manuel Lopes de Lima',
    'selma sant\'anna da fonseca': 'Selma Sant Anna Da Fonseca Sardinha',
    'giana laport alves de souza': 'Giana Laport Alves de Souza',
    'isis regina dos santos mendes': 'Isis Regina Mendes',
    'simone christina rebello barros': 'Simone Christina Rebello Barros',
    'kátia lúcia fentanez rodrigues mattos': 'kátia Lúcia Fentanez Rodrigues Mattos',
    'rejane de oliveira freitas silveira': 'Rejane de Oliveira Freitas Silveira',
    'deivid costa soares': 'Deivid Costa Soares',
    'filomena maria rates soares': 'Filomena Maria Rates Soares',
    'fernanda barbosa salgueiro': 'Fernanda Barbosa Salgueiro',
    'telma ardoim': 'Telma Ardoim',
    'erick de sousa marouço': 'Érick Marrouco',
    'wallace da silva carvalho': 'Wallace da Silva Carvalho',
    'ary sergio coutinho barbosa junior': 'Ary Sérgio Coutinho Barbosa Júnior',
    'camila ferreira de souza costa': 'Camila Ferreira de Souza Costa',
    'andré lourenço da silveira': 'André Lourenço da Silva',
    'douglas batista da silva': 'Douglas Batista da Silva',
    'cristiane pires motta': 'Cristiane Pires Motta',
    'raphael pacheco da rocha': 'Raphael Pacheco da Rocha',
    'athus martins salgado do amaral': 'Athus Martins Salgado do Amaral',
    'carlos figueiredo veiga': 'Carlos Figueiredo Veiga',
    'lucas antunes faria vieira': 'Lucas Antunes Faria Vieira',
    'joel teixeira dutra': 'Joel Teixeira Dutra',
    'letícia ecard rocha': 'Letícia Ecard',
    'joão jorge sarto neto': 'João Jorge Sarto Neto',
    'wellington marinho pereira': 'Wellington Marinho Pereira',
    'mônica saad madeira': 'Mônica Saad Madeira',
    'rodolfo gomes de araujo oliveira': 'Rodolfo Gomes de Araujo Oliveira',
    'rafael da silva moreira': 'Rafael da Silva Moreira',
    'luciano roberto padilha de andrade': 'Luciano Roberto Padilha de Andrade',
    'jaime luciano de souza': 'Jaime Luciano de Souza',
    'vânia das graças de vasconcellos': 'Vania das Graças de Vasconcellos',
    'luciana santos de oliveira': 'Luciana Santos de Oliveira',
    'fernando salgado amaral': 'Fernando Salgado do Amaral',
    'rafaela de oliveira ferreira': 'Rafaela de Oliveira Ferreira',
    'thiago pereira de abreu': 'Tiago Pereira de Abreu',
    'arith ramos dos santos': 'Arith Ramos dos Santos'
}